export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const GET_PREPARE_MEETING = "GET_PREPARE_MEETING";
export const GET_PREPARE_MEETING_SUCCESS = "GET_PREPARE_MEETING_SUCCESS";
export const GET_PREPARE_MEETING_FAIL = "GET_PREPARE_MEETING_FAIL";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_FAIL = "GET_SUPPLIERS_FAIL";

export const CREATE_MEETING = "CREATE_MEETING";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAIL = "CREATE_MEETING_FAIL";

export const UPDATE_MEETING_LIST = "UPDATE_MEETING_LIST";

export const MEETING = "MEETING";
export const MEETING_SUCCESS = "MEETING_SUCCESS";
export const MEETING_FAIL = "MEETING_FAIL";

export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAIL = "REMOVE_USER_FAIL";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL"; 

export const SAVE_NEW_USERS = "SAVE_NEW_USERS";
export const SAVE_NEW_USERS_SUCCESS = "SAVE_NEW_USERS_SUCCESS";
export const SAVE_NEW_USERS_FAIL = "SAVE_NEW_USERS_FAIL";

export const TRANSFER_USER = "TRANSFER_USER";
export const TRANSFER_USER_SUCCESS = "TRANSFER_USER_SUCCESS";
export const TRANSFER_USER_FAIL = "TRANSFER_USER_FAIL";

export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT";
export const REMOVE_DOCUMENT_SUCCESS = "REMOVE_DOCUMENT_SUCCESS";
export const REMOVE_DOCUMENT_FAIL = "REMOVE_DOCUMENT_FAIL";

export const UPDATE_DOCUMENTS = "UPDATE_DOCUMENTS";
export const UPDATE_DOCUMENTS_FAIL = "UPDATE_DOCUMENTS_FAIL";
export const UPDATE_DOCUMENTS_SUCCESS = "UPDATE_DOCUMENTS_SUCCESS";

export const UPDATE_MEETING = "UPDATE_MEETING";
export const UPDATE_MEETING_SUCCESS = "UPDATE_MEETING_SUCCESS";
export const UPDATE_MEETING_FAIL = "UPDATE_MEETING_FAIL"; 

export const DESTROY_LAST_OPEND_MEETING = "DESTROY_LAST_OPEND_MEETING";
export const DESTROY_LAST_OPEND_MEETING_PROCEED = "DESTROY_LAST_OPEND_MEETING_PROCEED";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const START_MEETING = "START_MEETING";
export const START_MEETING_SUCCESS = "START_MEETING_SUCCESS";
export const START_MEETING_FAIL = "START_MEETING_FAIL";

export const PAUSE_MEETING = "PAUSE_MEETING";
export const PAUSE_MEETING_SUCCESS = "PAUSE_MEETING_SUCCESS";
export const PAUSE_MEETING_FAIL = "PAUSE_MEETING_FAIL"; 

export const STOP_PAUSE_MEETING = "STOP_PAUSE_MEETING";

export const AWAY = "AWAY";
export const AWAY_SUCCESS = "AWAY_SUCCESS";
export const AWAY_FAIL = "AWAY_FAIL";

export const USER_START = "USER_START";
export const USER_START_SUCCESS = "USER_START_SUCCESS";
export const USER_START_FAIL = "USER_START_FAIL";

export const USER_PAUSE = "USER_PAUSE";
export const USER_PAUSE_SUCCESS = "USER_PAUSE_SUCCESS";
export const USER_PAUSE_FAIL = "USER_PAUSE_FAIL";

export const NOTE = "NOTE";
export const NOTE_SUCCESS = "NOTE_SUCCESS";
export const NOTE_FAIL = "NOTE_FAIL";

export const LINK="LINK";
export const LINK_SUCCESS = "LINK_SUCCESS";
export const LINK_FAIL = "LINK_FAIL";

export const REMOVE_LINK = "REMOVE_LINK";
export const REMOVE_LINK_SUCCESS = "REMOVE_LINK_SUCCESS";
export const REMOVE_LINK_FAIL = "REMOVE_LINK_FAIL";

export const STOP_USER_PAUSE = "STOP_USER_PAUSE";

export const SWAP_USERS = "SWAP_USERS";

export const END_MEETING = "END_MEETING";
export const END_MEETING_SUCCESS = "END_MEETING_SUCCESS";
export const END_MEETING_FAIL = "END_MEETING_FAIL";

export const STOP_USERS_PAUSE = "STOP_USERS_PAUSE";

export const LEAVE = "LEAVE";
export const LEAVE_SUCCESS = "LEAVE_SUCCESS";
export const LEAVE_FAIL = "LEAVE_FAIL";

export const SAVE_NEW_PLACE = "SAVE_NEW_PLACE";
export const SAVE_NEW_PLACE_SUCCESS = "SAVE_NEW_PLACE_SUCCESS";
export const SAVE_NEW_PLACE_FAIL = "SAVE_NEW_PLACE_FAIL";

export const SAVE_NEW_TITLE = "SAVE_NEW_TITLE";
export const SAVE_NEW_TITLE_SUCCESS = "SAVE_NEW_TITLE_SUCCESS";
export const SAVE_NEW_TITLE_FAIL = "SAVE_NEW_TITLE_FAIL";

